package Persistencia;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import InterfazGrafica.Principal;
import InterfazGrafica.conexion;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ADSI
 */
public class BuscarR extends javax.swing.JFrame {

    
    int CantidadRegistros;
    /**
     * Creates new form BuscarR
     */
    public BuscarR() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        caja_buscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Cantidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Buscar Nombre");

        caja_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_buscarActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar Base de Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(caja_buscar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
          
            
            conexion llave= new conexion();
        String ComandoSQL="select * from recepcionista";
        Statement sentencia = llave.getConnection().createStatement();
        
          ResultSet resultado = sentencia.executeQuery(ComandoSQL);
          
          
        
        while (resultado.next()) {
            
            CantidadRegistros=resultado.getRow();
                jTextArea.append(resultado.getObject(1).toString()+"\t"+resultado.getObject(2).toString()+"\t"+resultado.getObject(3).toString()+"\n");
            
            
        }
        
         Cantidad.setText("Cantidad de Registros: "+CantidadRegistros);            
            resultado.close();
            llave.desconectar();
        
        } catch (SQLException ex) {
            Logger.getLogger(BuscarR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void caja_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_buscarActionPerformed

        try {
           jTextArea.setText("");
           CantidadRegistros=0;
            conexion llave= new conexion();
            String ComandoSQL="select * from recepcionista where nombre like '%"+caja_buscar.getText()+"%'";
          //   JOptionPane.showMessageDialog(null,ComandoSQL);
            Statement sentencia = llave.getConnection().createStatement();

            ResultSet resultado = sentencia.executeQuery(ComandoSQL);

            while (resultado.next()) {
                CantidadRegistros=resultado.getRow();
                jTextArea.append(resultado.getObject(1).toString()+"\t"+resultado.getObject(2).toString()+"\t"+resultado.getObject(3).toString()+"\n");
            }
            
            Cantidad.setText("Cantidad de Registros: "+CantidadRegistros);            
            resultado.close();
            llave.desconectar();

        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Ha ocurrido un error");
        }
                                    


        // TODO add your handling code here:
    }//GEN-LAST:event_caja_buscarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Principal.bloquearR=(false);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    void ejecutar_operacion(){
        
        try {     

            conexion llave= new conexion();
            String ComandoSQL="select * from recepcionista where nombre like %"+caja_buscar.getText()+"%";
           Statement sentencia = llave.getConnection().createStatement();

            ResultSet resultado = sentencia.executeQuery(ComandoSQL);

            ResultSetMetaData resultadometadata = resultado.getMetaData();

            int cantidadColumnas = resultadometadata.getColumnCount();

            while (resultado.next()) {

                jTextArea.append(resultado.getObject(1).toString()+"\t"+resultado.getObject(2).toString()+"\t"+resultado.getObject(3).toString()+"\n");
                //JOptionPane.showMessageDialog(null,fila[i].toString());
            }
            resultado.close();
            llave.desconectar();

        } catch (SQLException ex) {
  //          Logger.getLogger(MostrarDoctores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JTextField caja_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
